# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tzm', models.IntegerField()),
                ('Tpm', models.IntegerField()),
                ('Tzco', models.IntegerField()),
                ('Tpco', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='data pomiaru')),
            ],
        ),
    ]
