# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizualizacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='Tpco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Tpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Tzco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Tzm',
            field=models.IntegerField(default=0),
        ),
    ]
