# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizualizacja', '0002_auto_20161029_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 16, 40, 41, 469000), verbose_name='data pomiaru'),
        ),
    ]
