# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizualizacja', '0004_auto_20161030_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='To',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 20, 42, 9, 364000), verbose_name='data pomiaru'),
        ),
    ]
