# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizualizacja', '0005_auto_20161114_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='Th',
            new_name='Th1',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='Tr',
            new_name='Th2',
        ),
        migrations.AddField(
            model_name='measurement',
            name='Tr1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Tr2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 15, 17, 39, 56, 582000), verbose_name='data pomiaru'),
        ),
    ]
